### ISSUE TITLE
data.js falls outside of src folder

### ISSUE THREAD

**Issue by kolya182** [bryantheastronaut/mernCommentBox#11]
Hello,
I'm new to react, and I was following a tutorial and got this compile error. As a solution, i moved data.js folder inside src folder. Is this is the right way of fixing the problem? Please advise. 

![screenshot 2017-08-08 00 05 12](https://user-images.githubusercontent.com/3277207/29060291-fbe69988-7bcd-11e7-84ca-b99ae34dc0b4.jpg)

**Comment by bryantheastronaut** [comment]
Yeah this is an issue that has come up with the new version of create-react-app requiring everything to be inside the `src/` dir. The correct way to fix is to move it into the `src/` folder and change all references to that folder to point to the new location. I will update the tutorial soon! Thanks for pointing this out!
