### ISSUE TITLE
route /api/comments goes to 404

### ISSUE THREAD

**Issue by aravishack** [bryantheastronaut/mernCommentBox#24]
i cloned this application , updated the Mlab creds and run it.
Application is not working because its showing the error,  **http://localhost:3000/api/comments not found.**
I am using the port number 3000 instead of 3001.

Could please help me in debugging this ?

**Comment by laurareyeslarrosa** [comment]
@Aravind-WMG you need to create your own mLab account (https://mlab.com/)
then create a database, get a user in it and then update the server.js with the database data
