### ISSUE TITLE
Project name can no longer contain capital letters

### ISSUE THREAD

**Issue by EJLearner** [bryantheastronaut/mernCommentBox#3]
I'm getting the following error when running the create-react-app command because of the capital letters in the project name. Can the name be changed to "mern-comment-box"?

![image](https://cloud.githubusercontent.com/assets/22520333/23828106/e1e0d304-0694-11e7-9fc5-00b3e8ce5762.png)

This is with the following versions:
create-react-app: 1.3.0
Node: 7.7.2
npm: 4.1.2

**Comment by bryantheastronaut** [comment]
Good catch! I wasn't aware that change had been made. Readme has been updated accordingly. Thanks!
