### ISSUE TITLE
PUT/DELETE Not working

### ISSUE THREAD

**Issue by bgalladian** [bryantheastronaut/mernCommentBox#4]
Hey there,

I was wondering if you could offer some insight on the PUT/DELETE methods in my code, it doesn't seem to be working.  Here is the link:

https://github.com/bgalladian/kicksstarter2

Any help would be appreciated!

EDIT: nvm I'm an idiot, got it working

**Comment by bryantheastronaut** [comment]
Glad to hear it!

**Comment by nickcastro** [comment]
Apparently i'm an idiot also - stuck on this same problem. @bgalladian, could you explain how you got it working?
